The first metric is crime. In this case, we are trying to build a measurement of the security degree of the community.                  
The measurement can be divided into two parts: the probability of encounter crime and how severe the crime is.                      
For the first part, we need to figure out the frequency of each type of crime and proportion of criminal in the whole population of the community.                
For the second part, we need to have a rank of the severe degree of differernt types of crime, and figure a weight to quantify the potential harm of these crimes. The weight will be represented by numbers between 0 and 100, where 100 means death.                     
And the final measurement will be built like this:         
            
1.Find out the proportion of criminal in the poplulation of community, namely the probability of encountering a criminal in the community.( a%)      
2.Use the frequency of different types of crime to predict what would be the next action of this criminal. (m% for murder, n% for robber and so on ) we assume that the type of crime won't convert to each other and even the slightest crime is intolerable.           
3.Times the fequency by the weight and add them together.(100m% for murder+70n% for robber...) The result will be taken as a criminal's personal
dangerous degree.        
4.Times the criminal dangerous degree by the probability of encountering a criminal, the result will be the community dangerous degree.                   
                
The lower the community dangerous degree, the better the security degree of the community is.

In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
crime = pd.read_csv("crime.csv")
list1=pd.DataFrame(crime.iloc[0:,[0,2,6,7]])
list1.head()

,Neighborhood,Population (2010),Part 1 Crime per 100 Persons (2010),Part 2 Crime per 100 Persons (2010)
0,Allegheny Center,933,7.6,15.1
1,Allegheny West,462,8.2,10.6
2,Allentown,"2,500",6.4,10.1
3,Arlington,"1,869",2.7,4.5
4,Arlington Heights,244,7.8,15.2

In [2]:
#this list shows the probability of encountering a criminal in the community.
# PEC=probability of encountering a criminal
a=list1.iloc[0:,2]
b=list1.iloc[0:,3]
thelist=[]
i=0
while i<=89:
    c=float(list1.iloc[i,1].replace(',',''))
    thelist.append(c)
    i=i+1
list1['population1']= thelist
d=list1.iloc[0:,4]
PEC=(a+b)/d
list2={'Neighborhood':list1.iloc[0:,0],'PEC':PEC}
x=pd.DataFrame(list2)
x1=x.sort_values(by="PEC")
x1

                 Neighborhood        PEC
75        Squirrel Hill North   0.000202
76        Squirrel Hill South   0.000238
55              North Oakland   0.000284
13                  Brookline   0.000363
67                  Shadyside   0.000481
36                 Greenfield   0.000590
62               Point Breeze   0.000677
10                      Bluff   0.000682
78            Stanton Heights   0.000739
7                   Beechview   0.000778
39              Highland Park   0.000844
5                  Banksville   0.000845
31                  Fairywood   0.000898
45              Lincoln Place   0.000930
15                    Carrick   0.000969
12           Brighton Heights   0.000994
19            Central Oakland   0.001084
54              New Homestead   0.001111
52           Mount Washington   0.001114
9                  Bloomfield   0.001161
88                   Westwood   0.001174
59                  Overbrook   0.001235
46   Lincoln-Lemington-Belmar   0.001290
51                Morningside   0.001405
49         Marshall-Shadeland   0.001456
22            Crafton Heights   0.001626
24           Duquesne Heights   0.001691
60                Perry North   0.001901
38                  Hazelwood   0.002015
17      Central Lawrenceville   0.002030
..                        ...        ...
26              East Carnegie   0.006140
23           Crawford-Roberts   0.006383
2                   Allentown   0.006600
35                 Glen Hazel   0.008380
6           Bedford Dwellings   0.008486
44                    Larimer   0.008796
41             Homewood South   0.009428
16  Central Business District   0.010278
50                Middle Hill   0.011951
25             East Allegheny   0.012079
11                    Bon Air   0.012376
66                  Ridgemont   0.012422
73              Spring Garden   0.012443
20             Chartiers City   0.012788
57          Northview Heights   0.012850
32                   Fineview   0.014008
53                 Mt. Oliver   0.015521
42              Homewood West   0.019560
37                       Hays   0.024309
0            Allegheny Center   0.024330
14       California-Kirkbride   0.026413
1              Allegheny West   0.040693
77                  St. Clair   0.055024
79             Strip District   0.084903
4           Arlington Heights   0.094262
30                     Esplen   0.109302
86                   West End   0.119685
56                North Shore   0.152475
70                South Shore  26.868421
21                    Chateau  33.063636

[90 rows x 2 columns]

In [3]:
a1=crime.iloc[0:,8]
a2=crime.iloc[0:,9]
a3=crime.iloc[0:,10]
a4=crime.iloc[0:,11]
a5=crime.iloc[0:,12]
a6=crime.iloc[0:,13]
a7=crime.iloc[0:,14]
k=a1+a2+a3+a4+a5+a6+a7
#PDD=personal dangerous degree
PDD=100*a1/k+95*a2/k+90*a3/k+90*a4/k+95*a5/k+90*a6/k+90*a7/k
list3={'neighborhood':crime.iloc[0:,0],'PDD':PDD}
y=pd.DataFrame(list3)
y1=y.sort_values(by="PDD").head()
y1.head()

         neighborhood        PDD
21            Chateau  90.000000
50        Middle Hill  90.500000
23   Crawford-Roberts  90.636943
10              Bluff  90.795455
6   Bedford Dwellings  90.800000

In [4]:
#CDD=community dangerous degree
CDD=PDD*PEC
list_final={'neighborhood':crime.iloc[0:,0],'CDD':CDD}
z=pd.DataFrame(list_final)
z1=z.sort_values(by="CDD").head()
z1.head()

           neighborhood       CDD
75  Squirrel Hill North  0.018687
76  Squirrel Hill South  0.022065
55        North Oakland  0.026189
13            Brookline  0.033251
67            Shadyside  0.044241

now's the time for natural enviroment. basically I'm using the similar method to quantify the degree of natural enviroments in every community.
firstly I will figure out the per capita land resources, which is merely the land area own by a single person in their communities.
secondly I will take another community dangerous degree based on three kinds of natural diasters as negative scores, and the community ne degree based on greenway and woodland as positive scores, and then minus negative scores from positives scores, to determine whether the land is "good" or "bad", and the degree of "good" or "bad". the result of this step will also be quantified.
finally I will times per capita land resources with the result of the second step, to determine how large the area of those "good" or "bad" lands a single preson will own in their communities.

In [5]:
import pandas as pd
import numpy as np
import geopandas as gpd
ne = pd.read_csv("ne.csv")
ne.head()

,Neighborhood,Sector #,Population (2010),Land Area (acres),Landslide Prone (% land area),Undermined (% land area),Flood Plain (% land area),# Street Trees,Park Space (acres),Park Space (% of land area),Park Space (acres/1000 pers.),Greenway (% of land area),Woodland (% of land area),Cemetery (% of land area)
0,Allegheny Center,3,933,134.4,0.0%,0.0%,0.2%,22,55.3,41.1%,59.2,0.0%,0.0%,0.0%
1,Allegheny West,3,462,90.2,9.3%,0.0%,2.3%,229,7.2,8.0%,15.5,0.0%,4.2%,0.0%
2,Allentown,6,"2,500",188.8,27.1%,90.4%,0.0%,87,39.4,20.9%,15.8,0.0%,12.3%,0.0%
3,Arlington,7,"1,869",300.8,41.4%,57.3%,1.5%,79,6.7,2.2%,3.6,0.0%,29.4%,7.3%
4,Arlington Heights,7,244,84.5,39.9%,61.2%,0.0%,3,0.0,0.0%,0.0,0.0%,41.8%,0.0%

In [6]:
#this is for the per capita land resources
listne1=[]
listne2=[]
listne3=[]
ine=0
while ine<=89:
    ane=float(ne.iloc[ine,2].replace(',',''))
    bne=float(ne.iloc[ine,3].replace(',',''))
    listne1.append(ane)
    listne2.append(bne)
    ine=ine+1
ne['pop1']=listne1
ne['la2']=listne2
ane1=ne.iloc[0:,14]
bne1=ne.iloc[0:,15]
PCLR=bne1/ane1
listne3.append(PCLR)
listf={'Neighborhood':ne.iloc[0:,0],'PCLR':PCLR}
xne=pd.DataFrame(listf)
xne1=xne.reindex(xne['PCLR'].abs().sort_values(ascending=False).index)
aa=pd.DataFrame(ne.iloc[0:,[4,13,14,15]])
xne1.head()

   Neighborhood       PCLR
21      Chateau  22.281818
70  South Shore   7.142105
37         Hays   3.093923
77    St. Clair   0.949282
56  North Shore   0.639934

In [10]:
# this is for the negative score: natural hazard
listnea=[]
listneb=[]
listnec=[]
listned=[]
one=0
while one<=89:
    cne=ne.iloc[one,4]
    dne=ne.iloc[one,5]
    ene=ne.iloc[one,6]
    cne1=float(cne[:-1])
    dne1=float(dne[:-1])
    ene1=float(ene[:-1])
    listnea.append(cne1)
    listneb.append(dne1)
    listnec.append(ene1)
    one=one+1
ne['lanslide1']=listnea
ne['undermined1']=listneb
ne['flood1']=listnec
cne11=ne.iloc[0:,16]
dne11=ne.iloc[0:,17]
ene11=ne.iloc[0:,18]
CDDne1=cne11*0.112*100+dne11*1*73+ene11*0.22*66
listned.append(CDDne1)
lists={'Neighborhood':ne.iloc[0:,0],'CDDne1':CDDne1}
yne=pd.DataFrame(lists)
yne1=yne.reindex(yne['CDDne1'].abs().sort_values(ascending=True).index)
asd=pd.DataFrame(ne.iloc[0:,[4,5,6,16,17,18]])
yne1

            Neighborhood    CDDne1
63    Point Breeze North     0.000
41        Homewood South     0.000
33            Friendship     0.000
48            Manchester     1.452
0       Allegheny Center     2.904
28          East Liberty     8.960
67             Shadyside    12.320
62          Point Breeze    42.560
42         Homewood West    44.800
9             Bloomfield    90.720
44               Larimer   112.000
19       Central Oakland   118.720
25        East Allegheny   124.320
18     Central Northside   136.640
1         Allegheny West   137.556
89               Windgap   153.692
40        Homewood North   167.900
39         Highland Park   188.036
20        Chartiers City   211.020
14  California-Kirkbride   219.520
10                 Bluff   242.304
31             Fairywood   243.348
71      South Side Flats   309.276
51           Morningside   311.528
23      Crawford-Roberts   327.740
85   Upper Lawrenceville   328.468
75   Squirrel Hill North   362.180
12      Brighton Heights   399.512
69         South Oakland   402.136
65         Regent Square   406.564
..                   ...       ...
27            East Hills  1868.800
87          West Oakland  2124.000
35            Glen Hazel  2354.944
50           Middle Hill  3255.800
58               Oakwood  3401.800
22       Crafton Heights  3428.760
82       Terrace Village  3442.340
72     South Side Slopes  3649.080
24      Duquesne Heights  3999.212
37                  Hays  4043.360
11               Bon Air  4219.004
54         New Homestead  4645.780
3              Arlington  4668.360
52      Mount Washington  4844.992
4      Arlington Heights  4914.480
77             St. Clair  5047.672
6      Bedford Dwellings  5435.220
66             Ridgemont  5486.440
59             Overbrook  5714.128
7              Beechview  5814.472
8            Beltzhoover  5837.452
88              Westwood  5981.040
13             Brookline  6448.560
84            Upper Hill  6519.400
5             Banksville  6662.460
45         Lincoln Place  6765.572
15               Carrick  6784.820
2              Allentown  6902.720
53            Mt. Oliver  7016.140
43             Knoxville  7293.820

[90 rows x 2 columns]

In [9]:
#CNED=community natural enviroment degree
flist=[]
slist=[]
tlist=[]
k=0
while k<=89:
    f=ne.iloc[k,11]
    g=ne.iloc[k,12]
    f1=float(f[:-1])
    g1=float(g[:-1])
    flist.append(f1)
    slist.append(g1)
    k=k+1
ne['greenway1']=flist
ne['woodland1']=slist
f11=ne.iloc[0:,19]
g11=ne.iloc[0:,20]
CNED=(f11+g11)*50
tlist.append(CNED)
listt={'Neighborhood':ne.iloc[0:,0],'CNED':CNED}
za=pd.DataFrame(listt)
za11=za.reindex(za['CNED'].abs().sort_values(ascending=True).index)
za11

                 Neighborhood    CNED
0            Allegheny Center     0.0
33                 Friendship     0.0
41             Homewood South     0.0
21                    Chateau     0.0
67                  Shadyside     0.0
63         Point Breeze North     0.0
56                North Shore     0.0
10                      Bluff     0.0
48                 Manchester     0.0
16  Central Business District     0.0
71           South Side Flats    10.0
9                  Bloomfield    25.0
43                  Knoxville    25.0
17      Central Lawrenceville    30.0
28               East Liberty    50.0
70                South Shore    70.0
50                Middle Hill    75.0
55              North Oakland   105.0
75        Squirrel Hill North   105.0
18          Central Northside   110.0
25             East Allegheny   130.0
79             Strip District   155.0
47        Lower Lawrenceville   165.0
14       California-Kirkbride   195.0
19            Central Oakland   195.0
1              Allegheny West   210.0
44                    Larimer   215.0
36                 Greenfield   220.0
23           Crawford-Roberts   240.0
42              Homewood West   280.0
..                        ...     ...
32                   Fineview   990.0
26              East Carnegie   990.0
22            Crafton Heights  1085.0
38                  Hazelwood  1150.0
89                    Windgap  1160.0
88                   Westwood  1160.0
6           Bedford Dwellings  1170.0
31                  Fairywood  1235.0
46   Lincoln-Lemington-Belmar  1325.0
78            Stanton Heights  1360.0
57          Northview Heights  1440.0
76        Squirrel Hill South  1445.0
3                   Arlington  1470.0
29                    Elliott  1530.0
81             Swisshelm Park  1560.0
45              Lincoln Place  1640.0
65              Regent Square  1665.0
58                    Oakwood  1690.0
7                   Beechview  1710.0
11                    Bon Air  1745.0
74      Spring Hill-City View  1765.0
60                Perry North  1880.0
66                  Ridgemont  1930.0
4           Arlington Heights  2090.0
24           Duquesne Heights  2305.0
73              Spring Garden  2320.0
77                  St. Clair  2465.0
54              New Homestead  3100.0
37                       Hays  3585.0
35                 Glen Hazel  4025.0

[90 rows x 2 columns]

In [11]:
finallist=[]
final=(tlist[0]-listned[0])*listne3[0]
ne['finalscore']=final
fin=ne.iloc[0:,21]
finalscore=ne.iloc[0:,[0,21]]
finalscore1=finalscore.reindex(finalscore['finalscore'].sort_values(ascending=False).index)
finalscore1

                Neighborhood    finalscore
35                Glen Hazel    680.617794
31                 Fairywood    613.794980
73             Spring Garden    340.240652
81            Swisshelm Park    216.810519
89                   Windgap    195.234043
46  Lincoln-Lemington-Belmar    190.371298
60               Perry North    187.374644
65             Regent Square    166.661406
20            Chartiers City    117.623291
39             Highland Park     76.462597
86                  West End     62.000378
76       Squirrel Hill South     60.914373
29                   Elliott     55.093985
57         Northview Heights     50.536977
68                  Sheraden     45.760196
62              Point Breeze     40.797544
80               Summer Hill     40.516403
42             Homewood West     36.631394
12          Brighton Heights     28.162739
44                   Larimer     16.975926
1             Allegheny West     14.143829
51               Morningside     10.849194
40            Homewood North      9.494323
61               Perry South      5.061188
78           Stanton Heights      2.750220
28              East Liberty      2.599876
19           Central Oakland      2.253556
25            East Allegheny      0.401536
85       Upper Lawrenceville      0.148780
63        Point Breeze North      0.000000
..                       ...           ...
58                   Oakwood   -268.854275
24          Duquesne Heights   -278.549412
22           Crafton Heights   -296.564912
72         South Side Slopes   -314.833022
52          Mount Washington   -344.940353
50               Middle Hill   -363.732958
43                 Knoxville   -374.983428
6          Bedford Dwellings   -406.650759
2                  Allentown   -474.848614
79            Strip District   -476.308932
7                  Beechview   -480.965467
3                  Arlington   -514.749432
13                 Brookline   -562.542092
84                Upper Hill   -590.032970
11                   Bon Air   -613.295794
15                   Carrick   -654.809332
88                  Westwood   -696.424858
59                 Overbrook   -707.226053
8                Beltzhoover   -729.472503
56               North Shore   -761.931010
54             New Homestead   -793.500400
53                Mt. Oliver   -809.887937
5                 Banksville   -860.925601
4          Arlington Heights   -978.149836
45             Lincoln Place  -1000.336302
37                      Hays  -1418.130387
66                 Ridgemont  -1739.194882
77                 St. Clair  -2451.684808
70               South Shore  -5542.045137
21                   Chateau -18344.264400

[90 rows x 2 columns]

In [12]:
aaafin=CDD*0.7+final*0.3

listresult={'Neighborhood':crime.iloc[0:,0],'result':aaafin}
result=pd.DataFrame(listresult)
result1=result.reindex(result['result'].sort_values(ascending=False).index)
result1

                Neighborhood       result
35                Glen Hazel   204.723937
31                 Fairywood   184.198225
73             Spring Garden   102.870181
81            Swisshelm Park    65.191968
70               South Shore    61.443476
89                   Windgap    58.847526
46  Lincoln-Lemington-Belmar    57.194207
60               Perry North    56.335208
65             Regent Square    50.392035
20            Chartiers City    36.100786
86                  West End    26.213123
39             Highland Park    22.992683
76       Squirrel Hill South    18.289757
29                   Elliott    16.832454
57         Northview Heights    15.984141
68                  Sheraden    13.866518
80               Summer Hill    12.356396
62              Point Breeze    12.283185
42             Homewood West    12.242389
12          Brighton Heights     8.512832
1             Allegheny West     6.841312
44                   Larimer     5.657381
30                    Esplen     4.331665
51               Morningside     3.345237
40            Homewood North     3.080714
61               Perry South     1.716793
0           Allegheny Center     1.421492
28              East Liberty     0.952952
25            East Allegheny     0.890383
78           Stanton Heights     0.872777
..                       ...          ...
82           Terrace Village   -61.328485
58                   Oakwood   -80.482134
24          Duquesne Heights   -83.454425
22           Crafton Heights   -88.864645
72         South Side Slopes   -94.314118
52          Mount Washington  -103.410061
50               Middle Hill  -108.362805
43                 Knoxville  -112.212581
6          Bedford Dwellings  -121.455867
79            Strip District  -137.485550
2                  Allentown  -142.031784
7                  Beechview  -144.239617
3                  Arlington  -154.177339
13                 Brookline  -168.739352
84                Upper Hill  -176.822987
11                   Bon Air  -183.196401
15                   Carrick  -196.380388
88                  Westwood  -208.851173
59                 Overbrook  -212.088144
8                Beltzhoover  -218.471825
56               North Shore  -218.835005
54             New Homestead  -237.979148
53                Mt. Oliver  -241.978705
5                 Banksville  -258.223521
4          Arlington Heights  -287.437693
45             Lincoln Place  -300.040217
37                      Hays  -423.868950
66                 Ridgemont  -520.954117
77                 St. Clair  -731.990789
21                   Chateau -3420.270229

[90 rows x 2 columns]